spring.application.name=cli
spring.main.web-application-type=none
spring.main.banner-mode=off
spring.main.log-startup-info=true
spring.shell.interactive.enabled=true
spring.security.oauth2.client.registration.spring.client-id=spring
spring.security.oauth2.client.registration.spring.client-secret=spring
spring.security.oauth2.client.registration.spring.authorization-grant-type=urn:ietf:params:oauth:grant-type:device_code
spring.security.oauth2.client.registration.spring.scope=message

spring.security.oauth2.client.provider.spring.issuer-uri=http://localhost:9090

logging.level.root=off

